config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'

  resources :users do
    resources :durations
    resources :bulks
  end

 

end

app/models/bulk.rb
class Bulk < ActiveRecord::Base
  belongs_to :user
end

app/models/duration.rb
class Duration < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :durations, dependent: :destroy
  has_many :bulks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  http_basic_authenticate_with :name => ENV['RAILS_WEB_USER'], :password => ENV['RAILS_WEB_PASS']

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bulks_controller.rb
class BulksController < ApplicationController
  
  def index
    redirect_to users_path
  end
  
  def create
    @user = User.find(params[:user_id])
    @bulk = @user.bulks.create(bulk_params)

    start_date = @bulk.start_date
    minute_values = @bulk.values.split(',').map{|x| x.to_i}
    minute_values.each_with_index { |val,index|
      if val > 0
        entry_date = start_date + index.days
        @user.durations.create(day: entry_date, minutes: val)
      end
    }

    redirect_to user_path(@user)
  end

  private
  def bulk_params    
    params.require(:bulk).permit(:start_date, :values)
  end

  
end

app/controllers/durations_controller.rb
class DurationsController < ApplicationController

  def index
    @durations = Duration.all
  end

  def show
    @duration = Duration.find(params[:id])
  end

  def edit
    @duration = Duration.find(params[:id])
  end

  def update
    @duration = Duration.find(params[:id])
    
    if @duration.update(duration_params)
      @user = @duration.user
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def new
    @duration = Duration.new    
  end

  def create
    @user = User.find(params[:user_id])
    @duration = @user.durations.create(duration_params)

    redirect_to user_path(@user)
  end

  def destroy
    @user = User.find(params[:user_id])
    @duration = @user.durations.find(params[:id])
    @duration.destroy
    redirect_to user_path(@user)
  end
  
  private
  def duration_params    
    params.require(:duration).permit(:day, :minutes)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    durations = Duration.all
    @grid = PivotTable::Grid.new do |g|
      g.source_data  = durations
      g.column_name  = :day
      g.row_name     = :user_id
      g.value_name   = :minutes
    end

    respond_to do |format|
      format.html
      format.csv {
        # Build and return CSV file using the pivot table
        out_data = CSV.generate do |csv|
          csv << @grid.build.column_headers.unshift('')
          @grid.build.rows.each do |row|
            user = User.find(row.header)
            user_name = user.username
            row_data = row.data.map{|n| n.nil? ? '' : n.minutes}
            row_data[0] = user_name
            csv << row_data
          end
        end

        send_data(out_data, :filename => 'walk_times.csv')
      }
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
 
    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def new
    @user = User.new    
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
 
    redirect_to users_path
  end
  
  private
  def user_params    
    params.require(:user).permit(:username, :first, :last)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    redirect_to users_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bulks_helper.rb
module BulksHelper
end

app/helpers/durations_helper.rb
module DurationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bulks/_form.html.erb
<%= form_for @bulk do |f| %>

  <% if @bulk.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@bulk.errors.count, "error") %> prevented creation.
      </h2>
      <ul>
        <% @bulk.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <table class="table-condensed">
  <tr>
    <th><%= f.label :user %></th>
    <td><%= f.number_field :user %></td>
  </tr>
 
  <tr>
    <th><%= f.label :start_date %></th>
    <td><%= f.date_field :start_date %></td>
  </tr>

  <tr>
    <th><%= f.label :values %></th>
    <td><%= f.text_field :values %></td>
  </tr>

  <tr>
    <th></th>
    <td><%= f.submit class: 'btn btn-primary' %></td>
  </tr>
  </table>
<% end %>

app/views/bulks/edit.html.erb
<h1>Edit Bulk</h1>

<%= render 'form' %>

<p><%= link_to 'View All Users', users_path %></p>

app/views/bulks/new.html.erb
<h1>Bulk Add Times</h1>
 
<%= render 'form' %>

<%= link_to 'View All Users', users_path %>

app/views/durations/_form.html.erb
<%= form_for [@duration.user,@duration] do |f| %>

  <% if @duration.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@duration.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @duration.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :day %><br>
    <%= f.date_field :day, class: 'input-sm' %>
  </p>

  <p>
    <%= f.label :minutes %><br>
    <%= f.text_field :minutes %>
  </p>

  <p>
    <%= f.submit class: 'btn btn-primary' %>
  </p>
 
<% end %>

app/views/durations/edit.html.erb
<h1>Editing entry</h1>

<%= render 'form' %>

<p><%= link_to user_path(@duration.user), class: 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-arrow-left"></span> Return to User
      <% end %>
</p>

app/views/durations/index.html.erb
<h1>Listing articles</h1>
 
<table>
  <tr>
    <th></th>
    <th>User</th>
    <th>Day</th>
    <th>Minutes</th>
  </tr>
 
  <% @durations.each do |duration| %>
    <tr>
      <td><%= link_to duration.id, duration_path(duration) %></td>
      <td><%= duration.user %></td>
      <td><%= duration.day %></td>
      <td><%= duration.minutes %></td>
      <td><%= link_to 'Show', duration_path(duration) %></td>
      <td><%= link_to 'Edit', edit_duration_path(duration) %></td>
      <td><%= link_to 'Delete', duration_path(duration),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>


</table>

<br/>

<%= link_to 'New Entry', new_duration_path %>

app/views/durations/new.html.erb
<h1>New Entry</h1>
 
<%= render 'form' %>

<%= link_to 'Back', durations_path %>

app/views/durations/show.html.erb
<p>
  <strong>User:</strong>
  <%= @duration.user %>
</p>

<p>
  <strong>Day:</strong>
  <%= @duration.day %>
</p>

<p>
  <strong>Minutes:</strong>
  <%= @duration.minutes %>
</p>

<p>
  <%= link_to 'Edit', edit_duration_path(@duration) %> |
  <%= link_to 'Back', durations_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Walk Tracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <table class="table-condensed">
  <tr>
    <th><%= f.label 'Display Name' %></th>
    <td><%= f.text_field :username %></td>
  </tr>
 
  <tr>
    <th><%= f.label :first %></th>
    <td><%= f.text_field :first %></td>
  </tr>

  <tr>
    <th><%= f.label :last %></th>
    <td><%= f.text_field :last %></td>
  </tr>

  <tr>
    <th></th>
    <td><%= f.submit class: 'btn btn-primary' %></td>
  </tr>
  </table>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render 'form' %>

<p><%= link_to 'View All Users', users_path %></p>

app/views/users/index.html.erb
<a href="https://github.com/dmcallas/walk-tracker"><img style="position: absolute; top: 0; right: 0; border: 0;" src="/fork_me.png" alt="Fork me on GitHub"></a>

<h1>Walking Tracker</h1>

<div class="container-fluid">

  <div class="row">
    <div class="col-sm-12">

      <table class="table-striped table-condensed">
	<tr>
	  <th></th>
	  <% @grid.build.column_headers.each do |head| %>
	  <th>
	    <%= head.strftime('%a') %><br/>
	    <%= head.strftime('%-m/%-d') %>
	  </th>
	  <% end %>
	  <th>Total</th>
	</tr>
	<% @grid.build.rows.sort_by{|row| row.total}.reverse.each do |row| %>
	<tr>
	  <% user = User.find(row.header) %>
	  <th><%= link_to user.username, user_path(user) %></th>
	  <% row.data.each do |item| %>
	  <% if item %>
	  <td><%= item.minutes %></td>
	  <% else %>
	  <td></td>
	  <% end %>

	  <% end %>
	  <th><%= row.total %></th>
	</tr>
	<% end %>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12">
      <%= link_to 'Download table as CSV', users_path(format: "csv"), class: 'btn btn-primary' %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12">
      <%= column_chart @users.map{|user| {name: user.username, data: user.durations.reject{|d| d.day.nil?}.sort_by{|d| d.day}.map{|d| [d.day,d.minutes] }}} %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12">
      <%= link_to 'Add a New User', new_user_path, class: 'btn btn-primary' %>
    </div>
  </div>

</div>

app/views/users/new.html.erb
<h1>New User</h1>
 
<%= render 'form' %>

<%= link_to 'View All Users', users_path %>

app/views/users/show.html.erb
<div class="container-fluid">
  
  <div class="help-block"></div>
  
  <div class="row">
    <div class="col-sm-12">
      <%= link_to users_path, class: 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-arrow-left"></span> Return to All Users
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <h1>
	<%= @user.first %> <%= @user.last %> (<%= @user.username%>)
<%= link_to 'Edit', edit_user_path(@user), class: 'btn btn-sm btn-primary' %>
      </h1>
    </div>
  </div>
  
  <div class="row">
    <div class="col-sm-12">
      <%= line_chart @user.durations.reject{|d| d.day.nil?}.sort_by{|d| d.day}.map{|d| [d.day,d.minutes] }, xtitle: "Day", ytitle: "Minutes" %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-1"></div>

    <div class="col-sm-5">
      <h2>Walk Times</h2>
      <%= form_for([@user, @user.durations.build]) do |f| %>

      <table class="table-striped table-condensed">
	<tr>
	  <th><%= f.label :day %></th>
	  <th><%= f.label :minutes %></th>
	  <th></th>
	</tr>

	<tr>
	  <td>
	    <%= f.date_field :day, value: Time.now.strftime('%Y-%m-%d'), class: 'input-sm' %>
	  </td>
	  <td>
	    <%= f.number_field :minutes, min: 0, max: 999, class: 'input-sm' %>
	  </td>
	  <td>
	    <%= f.submit 'Add', class: 'btn btn-primary' %>
	  </td>
	</tr>

	<% @user.durations.reject { |duration| duration.day.nil? }.sort_by {|duration| duration.day}.reverse.each do |duration| %>

	<tr>
	  <td>
            <%= duration.day.strftime('%m/%d/%Y') %>
	  </td>

	  <td>
            <%= duration.minutes %>
	  </td>
	  <td>
 	    <%= link_to edit_user_duration_path(@user,duration) do %>
	    <i class="glyphicon glyphicon-pencil"></i>
	    <% end %>
	    &nbsp;
	    <%= link_to  [duration.user, duration],
		method: :delete,
		data: { confirm: 'Are you sure?' } do %>
	    <i class="glyphicon glyphicon-trash"></i>
	    <% end %>
	  </td>
	</tr>
	<% end %>
      </table>
      <% end %>
    </div>
    <div class="col-sm-1"></div>
    <div class="col-sm-5">
      <h2>Add Multiple Times</h2>
      <p>Select the <i>first</i> day you will be entering time for in the date field. Then enter times, separating them with a comma. If you skipped a day, enter a zero for that day.</p>
      <%= form_for([@user, @user.bulks.build]) do |f| %>
      <%= f.label 'First Day In List' %>
      <%= f.date_field :start_date, value: '2016-07-01', class: 'input-sm' %>
      <br/>
      <%= f.label :values %>
      <%= f.text_field :values, min: 0, max: 999, class: 'input-sm' %>
      <br/>
      <%= f.submit 'Add Times', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>

  <div class="help-block"></div>

  <div class="row">
    <div class="col-sm-12">
      <%= link_to users_path, class: 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-arrow-left"></span> Return to All Users
      <% end %>
    </div>
  </div>

</div>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>